using System;
using System.Collections.Generic;
using System.IO;

namespace Tests
{
    public class TestFileReader : IFileReader
    {
        public IEnumerable<string> fileLines = new List<string> ()
        {
            ">read_0",
            "CAGCAGCAGCGGTTATACGGATAGAATAAGCGTTTAACATAATAAAAAGGCCTAAAAAGTATGTAGATGGAAAAAAACAA",
            ">read_1",
            "TGTAGCTCAATGGTAGAGCAAGTCACTGTTAATGACCTGATAGTGGTTCGATTCCACTCAATAACGATAAAAATATATAT",
            ">read_2",
            "AAGTCACTGTTAATGACCTGATAGTGGTTCGATTCCACTCAATAACGATAAAAATATATATAATGAGTTTGATGTTAGCT",
            ">read_3",
            "CTAGATCTATATAATTTATCTAGAAATCAAAGTATCCAGAAACATTTTTTAAGTGTTTCTTAATTAAAGATACATGACGC",
            ">read_4",
            "TTAAACAAAGTTTAAAAAAGTTATTAAATAATCTTAATGATCTTTTCATCTACCCTAAAAATATTGAATCCTTTTAAAAT",
            ">read_5",
            "ATAATATATTTGCTCATCCTAGATTTAAAGAATTTAGTAAAACTATTACTTTAGGTTTAAATTCAAATAATAATTTAAAT",
            ">read_6",
            "GTAAAAAAAGGTCAAATTCCTTTTCACCGAAAACTGAAGGGTTTTGACTTAAAAAGCTTAGCTTAAGTCAAATAAAGTAA",
            ">read_7",
            "AAAGTAACAATCTCTAAGCTAATAAATAGTGATGAGTAAATCTTAACGGATCTTAAAATAAAAGTTTTATTGAATAGAAA",
            ">read_8",
            "AAAAAATAATATTTTCTGGAGAAAGGCATCAAAAATTTAACGGATCTTAAACTTAATACTTAAACTTTGGCAGTATTTTA",
            ">read_9",
            "AAAATTCTCTTTTACTCAATGGTTAGTAGGATTTACTGATGGTGATGGTTGTTTTAGTATTTCAAAACAAAAAATAAAAA"
        };

        public IEnumerable<string> ReadLines (string filePath)
        {
            foreach (var line in fileLines)
            {
                yield return line;
            }
        }
    }
}